### ISSUE TITLE
A wonderful work， can I get a map without tag on the bottem right?

### ISSUE THREAD

**Issue by jyC23333** [chrieke/prettymapp#38]
And could this script add names on the buildings, waters...?

**Comment by chrieke** [comment]
Hi @jyC23333 Thank you for the kind words. Since the art is based on OpenStreetMap data and the prettymaps project, attribution should be kept. If you decide to change the code to remove the attribution for your own private prints, that is certainly up to you.

> And could this script add names on the buildings, waters...?

Could you clarify what you mean by this? Adresses over all buildings etc?

**Comment by jyC23333** [comment]
@chrieke Hi, I want to add names of the buildings on the map.

for example, if I plot a map of La Sagrada Familia in Barcelona, I want to show its name like this:
![image](https://github.com/chrieke/prettymapp/assets/110331827/f9a50a40-709c-4ad1-b419-2ca69216c292)

**Comment by chrieke** [comment]
Okay understand. I think it is easier if you just produce the map you want and then overlay the text for the specific buildings in some image editing tool, e.g. Photopea. The prettymapp app or manipulating the Python code would essentially have to do the same. It would require too many controls to filter for the specific building titles.

**Comment by jyC23333** [comment]
Thanks a lot！
